name: Receive and Save asw Token

on:
  repository_dispatch:
    types: [update-asw-token]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install jq
        run: |
          sudo apt update >>/dev/null
          sudo apt install jq -y

      - name: install jo
        run: |
          sudo apt install gcc git automake autoconf -y
          git clone 'https://github.com/jpmens/jo.git' '/tmp/jo'
          echo 'cd /tmp/jo' >>/tmp/jo_install.sh
          echo 'autoreconf -i' >>/tmp/jo_install.sh
          echo './configure' >>/tmp/jo_install.sh
          echo 'make check' >>/tmp/jo_install.sh
          echo 'make install' >>/tmp/jo_install.sh
          chmod -R 0755 '/tmp/jo_install.sh'
          sudo '/tmp/jo_install.sh'

      - name: Save to file
        run: |
          jo status=0 token="${{ github.event.client_payload.token }}" date="$(date +%s)" | jq >./asw
          
      - name: save caches if local change
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add asw
          if ! git diff --staged --exit-code 1>>/dev/null; then
            git commit -m "Update asw token $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
